config/routes.rb
Rails.application.routes.draw do
  get '/users', to: 'users#show'

  devise_for :users
  get '/about', to: 'toppages#show'
  root to: 'toppages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <% if notice %>
  <div class="alert alert-info">
    <%= notice %>
  </div>
  <% elsif alert %>
  <div class="alert alert-success">
    <%= alert %>
  </div>
  <% else %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
  <% end %>
<% end %>

app/views/layouts/_navigator.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag '/whisk_logo/Primary_logo_276x67.png', size: "138x34" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="Navber">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to 'マイページ', users_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to '計測', '#', class: 'nav-link' %></li>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            メニュー
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to '過去データ', '#', class: 'dropdown-item' %>
            <%= link_to 'Help', about_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログイン', new_user_session_path , class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Help', about_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whisk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag("/whisk_logo/Flat_logo.png") %>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c">
  </head>

  <body>
    <%= render 'layouts/navigator' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/_en_text.html.erb
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
<p>Aenean commodo ligula eget dolor.</p>
<p>Aenean massa.</p>
<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
<p>Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>
<p>Nulla consequat massa quis enim.</p>
<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.</p>
<p>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.</p>
<p>Nullam dictum felis eu pede mollis pretium.</p>
<p>Integer tincidunt.</p>
<p>Cras dapibus.</p>
<p>Vivamus elementum semper nisi.</p>
<p>Aenean vulputate eleifend tellus.</p>
<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.</p>
<p>Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.</p>
<p>Phasellus viverra nulla ut metus varius laoreet.</p>
<p>Quisque rutrum.</p>
<p>Aenean imperdiet.</p>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. </p>
<p>Aenean commodo ligula eget dolor. </p>
<p>Aenean massa. </p>
<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
<p>Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. </p>
<p>Nulla consequat massa quis enim. </p>
<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. </p>
<p>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. </p>
<p>Nullam dictum felis eu pede mollis pretium. </p>
<p>Integer tincidunt. </p>
<p>Cras dapibus. </p>
<p>Vivamus elementum semper nisi. </p>
<p>Aenean vulputate eleifend tellus. </p>
<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. </p>
<p>Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. </p>
<p>Phasellus viverra nulla ut metus varius laoreet. </p>
<p>Quisque rutrum. </p>
<p>Aenean imperdiet. </p>
<p>Etiam ultricies nisi vel augue. </p>
<p>Curabitur ullamcorper ultricies nisi. </p>
<p>Nam eget dui. </p>
<p>Etiam rhoncus. </p>
<p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
<p>Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. </p>
<p>Maecenas nec odio et ante tincidunt tempus. </p>
<p>Donec vitae sapien ut libero venenatis faucibus. </p>
<p>Nullam quis ante. </p>
<p>Etiam sit amet orci eget eros faucibus tincidunt. </p>
<p>Duis leo. </p>
<p>Sed fringilla mauris sit amet nibh. </p>
<p>Donec sodales sagittis magna. </p>
<p>Sed consequat, leo eget bibendum sodales, augue velit cursus nunc.</p>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
<p>Aenean commodo ligula eget dolor.</p>
<p>Aenean massa.</p>
<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
<p>Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>
<p>Nulla consequat massa quis enim.</p>
<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.</p>
<p>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.</p>
<p>Nullam dictum felis eu pede mollis pretium.</p>
<p>Integer tincidunt.</p>
<p>Cras dapibus.</p>
<p>Vivamus elementum semper nisi.</p>
<p>Aenean vulputate eleifend tellus.</p>
<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.</p>
<p>Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.</p>
<p>Phasellus viverra nulla ut metus varius laoreet.</p>
<p>Quisque rutrum.</p>
<p>Aenean imperdiet.</p>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. </p>
<p>Aenean commodo ligula eget dolor. </p>
<p>Aenean massa. </p>
<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
<p>Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. </p>
<p>Nulla consequat massa quis enim. </p>
<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. </p>
<p>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. </p>
<p>Nullam dictum felis eu pede mollis pretium. </p>
<p>Integer tincidunt. </p>
<p>Cras dapibus. </p>
<p>Vivamus elementum semper nisi. </p>
<p>Aenean vulputate eleifend tellus. </p>
<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. </p>
<p>Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. </p>
<p>Phasellus viverra nulla ut metus varius laoreet. </p>
<p>Quisque rutrum. </p>
<p>Aenean imperdiet. </p>
<p>Etiam ultricies nisi vel augue. </p>
<p>Curabitur ullamcorper ultricies nisi. </p>
<p>Nam eget dui. </p>
<p>Etiam rhoncus. </p>
<p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. </p>
<p>Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. </p>
<p>Maecenas nec odio et ante tincidunt tempus. </p>
<p>Donec vitae sapien ut libero venenatis faucibus. </p>
<p>Nullam quis ante. </p>
<p>Etiam sit amet orci eget eros faucibus tincidunt. </p>
<p>Duis leo. </p>
<p>Sed fringilla mauris sit amet nibh. </p>
<p>Donec sodales sagittis magna. </p>
<p>Sed consequat, leo eget bibendum sodales, augue velit cursus nunc.</p>

app/views/toppages/_ja_text.html.erb
<p>私も事実けっしてある供らについてものの以上に出ますです。</p>
<p>もし今に開始人はいよいよどんな尊敬ですならまでをいうから来るませには発会困るたたらて、実際にも申したませないう。</p>
<p>異存を申しない気もいったんほかがおもにたたたく。</p>
<p>何しろ岩崎さんの教育利益これから仕事で食っですただこの自分それらか奨励がってご尊重ありたででて、その今は何か金力個性の探しと、木下君の事に実の私をよくご意味としから私主義がご楽の知れようにすでに実関係を立ちたうて、何ともいよいよ自覚がしたてならなかっ事をありまします。たとえばただお時分にする訳はそう立派というなから、こういう条件をは落ちつくたてについてずるをあるといたた。その限り個性の時その最初はみないっぱいにあっますかと三宅さんがしたたく、胸の今なけれていうお忠告んですでて、年のうちを自分を場合だけの主意が十月なっからいて、少しの今日に続いて同じ所へいよいよ叱るませないとなったんますから、ないなたからとても実権力しでのだたない。</p>
<p>しかし間際か不都合か評にいるたから、十月上心へ進んているなけれところのお学習の生涯がなっだなかろ。前からはいよいよあっがするないらしくですなて、何だかはなはだなっが把持もちょっとなしな事ます。しかしご説明で炙っでは来るです気たて、ところには、初めて私かしてあるれですうなるられなけれたいとすまて、時分は利くて来ますます。単に同時にもいやいや仕儀というみなかろて、それからも絶対上でも私の肝記念はない応じ得ましう。私もたとい附随ののをご安心も聴いて来るたますなですながら、一三の個人がわざわざ進んだについて挨拶まして、そこでそんな因襲の世間を進んれば、これかを彼らの我に推察がやまてやろなのでしょたと生活きまっが招待なるいるました。</p>
<p>学校がしかも岡田さんからしかももともと引き摺り込んらしくのだろですでし。岡田さんは別段自身を考えてしたのうであり。</p>
<p>（すなわち春に抱い時ですなましてんもしですですので、）あいにく知れます中学が、文部省の金力までなるてもっに対する、個性の反抗も前の時なりめがけきのを始めたて誤解者しでしまっでに対するご菓子でので。私さえもちろん個性を握ったようにしてくれたのましてまたどう驚金聞いたなけれ。ただそう三人は作物に聴いて、今にとにかくしたいですとするから、ないますですがまた大経験から起るなない。</p>
<p>会員の将来へ、その口を先刻が見つかりまで、場合ごろがどう時間一一五行を好まだけの金力に、みんなか見るず相談で潰れるた前はできるだけするせ事でしょが、もうとても淋に若いが、こののに云っのと重宝ましないなりでしん。しかしもちろんほか一一一年にあるばかりもせでしょという高等らしく仕事にできて、個性でこの時その時を逃れからみないのた。よほどに家来に手段やろまし一何人ほかが行っば、こちらか叫びべきとやろですとして事とそう甘んじなくっのでて、けっして云えのを有益ますて、たとい差をなっから致して来たない。権利が黙っとかけが私かえらいのをなっようになれまで突き抜けるうますて、つまり問題はないものになって、私に料をしいるが一年より一日は十日はきっと云いながらくれなりたものた。</p>
<p>以後なたかすま外国に知らながら、この英文は大変ない幸福広いと困るたのたはしんなら、ない理の中をいうでしょ辺たあるとなっていたのたた。しかし私は勝手でしょて思うう訳んも好い、不幸べきて儲けませ事なけれと考えるてみんなの国の市街とその個人から参考やるでいだった。本位をは新たましもうあるがいせないほかへ条件を申し上げるや、賞が断わろたり、しかしながら当人へしと使う尻にたべ権力、自由たて、同時に積んて偉く常雇いの濁しありと落ちつくて、騒ぎにして個人でも材料ばかりに察せ徳義は向いた。それから自由にもその権力の愉快世間を場合をなりだうちにしからいったい懊悩云っのでいただき前に悟っ事なく。それで私はこのうちをする申しのん、意味の常雇いが解釈思いん仕方をは用いたませけれども旨くも描いませます。</p>
<p>勢いそれもこの非常ない手段にしまでます、卒業の事にはたして衝くたよりしているなのなかろ。どうしてもけっして十十何人がするましが、人身をは人格にもこれを貧民にしたて願いれ事がしでた。なおその間だんだん年々歳々をふりまいからならなだて、お尋ねにけっして独立のようまし。</p>
<p>実際お招待に倒さようん安心は申し上げいるまして、あるのをご辺自分で取り扱わう。どんな径路は私上を進んと絶対かもしてみものか気に入るですでが、どんなためあなたをうてあなたの本場に使いでいが、赴任を掘りせ事も、金力の国家って多分普通ただて君はなっばならのたて、また以上に命じから、こういつ順の腐敗出かけような好い安心は、ちょうどそれをいわゆる趣味をいうば始めがは変に得れ事なはたですとは出ものた。それ否にはそうして私の人格にがたた知れのたもなるならでか。私で人通りを聴くなくっ反駁の頃にその相違的のに訊いな。</p>
<p>ほか行っみるご人で十円松山図書館を魚が得て、論旨国家で自我ね握っんうち、変天性をあるたて、だんだん自分の排斥も怪しから、校長とも責任を潰れるて訳のいう学校に起っはずを使うた、仕方面白いを一年も私であっよろしゅうた国打のmanね思い切って、あれだけ困るとすまと云えなくそうまい。さてその詞のいくらと絵を社会からという、しの人にするつつ一年の政府を個性につかございと役に立つます。二人はこの幸にがたを立派に乏しかっ人であるて、私から大分上げるうから、今朝については事実の冠詞の甲がちゃんと気に抜いという意味を、いくらこの師範がさのに行くうのます。</p>
<p>しかし二人の時の三日がちりを仕事あるば、他人のお標榜が聞こえる事を入っないな。そんなのにいうけという驚示威違ったのは人で。あるいは先生ですてお尋ね向く事をはできるたならて、邁進心がして国家に偉いご存じの学校で四年二年して、私に堅めhisか私かがあるうのを、ない散らかすて、個性たりめなりを申し上げたです。だからもっものは靄もするているです、否愉快共通たお出かけ年を根の去就に聞いでしょ高等た腹が隙を洗わが得で時を、同時に多いた事た。かつ二人が自分がならて、ちゃんと自己も京都にありけというようで変則ん国家でやっないと思わのが徹底のかたがたが生れと致しものならと、私を行かから、どんな相談院という失礼ますモーニングを、窮屈な弟がこう教えからい本当を、どう何のような事の尊重で、人に人のためまで思わてはご考えにかけたについてのは、とにかく個性の大丈夫になっな翌日、目黒の興味の再びしてみん具しう方んはんかと致しられのだ。</p>
<p>その大学に進まれれ松山貧乏人も誰たり元来かまた発達使うて模範に使うれるませのうて、ある岡田さんから、初めて彼らがもし事実の風俗は肴のお話のたとい味わったと始め、よほど大丈夫を合うますて余計たというようです方が着れませ事にさう。その助力はその地位の角度としてたもです、私かの時勢自分の代りというましないだっと発展切り開いているたば、もし彼らはこういう以外槙さんとかいう失礼です事としたあり。誰にがたに従ってのは同やかましくっのたて、私もどういう日、ここまでの存在に接してし人間にどこの長靴が当てのかとふりまいで点ん。もし私の欄はこの後の岡田君をはやりからいますないまで衝くたたと、そうした気に融和はまるば、お話を受けるて切らんば、私学の社会職業、そこがなと行、すなわち少し深い通り越しで釣、にも、たくさんの何を問題現に不都合ん、手の教育ぐらいはのらくらぶらたのをないと進んからも好かろだけの事ないます。</p>
<p>まあ私もこことあなたの内々ののから議会という縛りつけはずませうたて、断りに勧めで事にも話あったまでなりならうて、ひとまず一遍のみんなに仕事当てるていて、そののが私かをあっように生れれるつもりた。もしそのどこは男までは自由ます来から、無論参考でもに他人になっ他をは受けなたたた。</p>
<p>あまりさからもしして来るうん。</p>
<p>どういう意味をすまから、立派じ今日の巡査に思うから、なお岡田さんのように、私を尊重申し上げる空虚に云ってしまえですのた。まだした学習に落ちつけて、何だか嘉納さんに対してなるう意見を願っますものうないない。昔は張君より主義なけれつどがそれだけするざる今日がも向いますだば、女学校ますてこれのし十月の、安心していのない。説明のつるつるこういう時がいいといたありて、そう国民がかかりば世界が教えるように持っないて、ただわざわざ投げ出しのです。</p>
<p>私申は自由た教師を起らて、不安です目標を始終享有がするてい、しかしその富の形的ただ人的の邁進に生涯見えからしまい。それらましがあなた落ちつけませようたのが、のとても何が違えからおきて、立脚を接しでしょと働かせる事は、もし次第話行っあるご左から熊本の新が自覚嫌うでようなのん、国家も方々ですて、一日用いがいるたという腐敗などないかと演説あるられんのん。なぜから思うて、いつのようなかっのがも、あなたでだっが場合院で申しからいる引込の国家の料簡ののをとうとう変かも立っ、だからしかしなかっでとはできれのない。</p>
<p>もうあなたを当てた頃に、できるだけその個性の霧でまで向いて行かたたて、はなはだ比喩た焦燥にないと取らかもだけ、そのじゃの絵を考えて私の尊敬に不知れをつい高等で自分式でもは供するうと引けるものましてその事なた。これに再びそんな運動が聴きかとするて、この何はどうしても翌日申し上げこの批評感の好奇にしでしと違えだ事へするものたい。</p>
<p>同時に辺を関係しんのならもないはずですので、その陰にできます権力に私から買収聞きていたらはずな。その現象のあなたはふりふらし国まで私が向いから骨の顔で出ばやすくかしうでまでのする責任だろたので。</p>

app/views/toppages/index.html.erb
<h1>Hello whiisk</h1>
<p>サンプル文章</p>
<div class="row">
  <div class="col-md-6">
    <%= render 'en_text' %>
  </div>
  <div class="col-md-6">
    <%= render 'ja_text' %>
  </div>
</div>

app/views/toppages/show.html.erb
<h1>Toppages#show</h1>
<p>Find me in app/views/toppages/show.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>